# Generated by Django 3.2.18 on 2023-03-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coller_pallates', '0002_colorpaletterevision_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colorpalette',
            old_name='accent_colors1',
            new_name='accent_color1',
        ),
        migrations.RenameField(
            model_name='colorpalette',
            old_name='accent_colors2',
            new_name='accent_color2',
        ),
        migrations.RenameField(
            model_name='colorpalette',
            old_name='accent_colors3',
            new_name='accent_color3',
        ),
        migrations.RenameField(
            model_name='colorpalette',
            old_name='accent_colors4',
            new_name='accent_color4',
        ),
    ]
